includes:
- ./defaults.yaml

checkpoint:
  resume_pretrained: true
  resume_zoo: visual_bert.pretrained.coco

training:
  seed: 48425275
  early_stop:
    enabled: true

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8


